import { useEffect, useRef, useState } from "react";
import type { InputItem } from "@suwol/shared";
import { FeatureLayout, RangeField, useFfmpegAvailability, useHandlePreview, useHistory, type FeatureProps } from "../shared";

function Waveform({ url, start, duration }: { url?: string; start: number; duration: number }) {
  const canvas = useRef<HTMLCanvasElement>(null); const [message, setMessage] = useState("오디오 파일을 선택하세요.");
  useEffect(() => { let context: AudioContext | undefined; let active = true; if (!url) return; void fetch(url).then((response) => response.arrayBuffer()).then(async (data) => { context = new AudioContext(); const buffer = await context.decodeAudioData(data); if (!active || !canvas.current) return; const drawing = canvas.current; drawing.width = 900; drawing.height = 180; const pen = drawing.getContext("2d"); if (!pen) return; pen.clearRect(0, 0, drawing.width, drawing.height); pen.fillStyle = "#0f172a"; pen.fillRect(0, 0, drawing.width, drawing.height); const samples = buffer.getChannelData(0); const step = Math.max(1, Math.floor(samples.length / drawing.width)); pen.strokeStyle = "#38bdf8"; pen.beginPath(); for (let x = 0; x < drawing.width; x += 1) { let peak = 0; for (let index = 0; index < step; index += 1) peak = Math.max(peak, Math.abs(samples[x * step + index] ?? 0)); const y = (1 - peak) * drawing.height / 2; pen.moveTo(x, y); pen.lineTo(x, drawing.height - y); } pen.stroke(); const total = buffer.duration || 1; pen.fillStyle = "rgba(244,114,182,.35)"; pen.fillRect(Math.min(drawing.width, start / total * drawing.width), 0, Math.min(drawing.width, duration / total * drawing.width), drawing.height); setMessage(`${buffer.duration.toFixed(2)}초 · Web Audio 미리듣기만 사용`); }).catch(() => setMessage("이 브라우저에서 waveform을 디코드하지 못했습니다. 실제 변환은 FFmpeg Worker에서 실행됩니다.")); return () => { active = false; void context?.close(); }; }, [url, start, duration]);
  return <div className="waveform"><canvas ref={canvas} /><small>{message}</small></div>;
}

export default function AudioToolkitFeature(props: FeatureProps) {
  const audioItems = props.input?.items.filter((item) => item.mimeType?.startsWith("audio/") || /\.(wav|mp3|flac|ogg|m4a)$/i.test(item.name)) ?? [];
  const [selected, setSelected] = useState<InputItem | undefined>(audioItems[0]); const preview = useHandlePreview(selected, 32 * 1024 * 1024); const player = useRef<HTMLAudioElement>(null);
  const ffmpeg = useFfmpegAvailability();
  const history = useHistory(props.options, props.onReplaceOptions, 50); const commit = (patch: Record<string, unknown>) => history.commit({ ...props.options, ...patch });
  const start = Number(props.options.start ?? 0); const duration = Number(props.options.duration ?? 1);
  const center = <div className="audio-center"><div className="editor-toolbar"><button disabled={!history.canUndo} onClick={history.undo}>↶ Undo</button><button disabled={!history.canRedo} onClick={history.redo}>↷ Redo</button><button onClick={() => { if (player.current?.paused) void player.current.play(); else player.current?.pause(); }}>재생 / 일시정지</button><button onClick={() => { if (player.current) { player.current.currentTime = start; void player.current.play(); } }}>선택 구간 반복</button></div>{preview.url && <audio ref={player} controls src={preview.url} loop={props.options.previewLoop === true} onTimeUpdate={(event) => { const end = start + duration; if (props.options.previewLoop === true && event.currentTarget.currentTime > end) event.currentTarget.currentTime = start; }} />}<Waveform url={preview.url} start={start} duration={duration} /><div className="timeline-selection"><label>시작<input type="range" min="0" max="120" step="0.01" value={start} onChange={(event) => commit({ start: Number(event.target.value), operation: "trim" })} /></label><label>길이<input type="range" min="0.01" max="120" step="0.01" value={duration} onChange={(event) => commit({ duration: Number(event.target.value), operation: "trim" })} /></label></div></div>;
  const right = <div><label>작업<select value={String(props.options.operation ?? "export")} onChange={(event) => commit({ operation: event.target.value })}><option value="export">변환·내보내기</option><option value="trim">구간 자르기</option><option value="delete">구간 삭제</option><option value="normalize">정규화</option><option value="fade">Fade in/out</option><option value="volume">볼륨</option><option value="channel">Mono/Stereo</option><option value="speed">속도</option><option value="reverse">역재생</option><option value="silence">무음 제거</option><option value="loop">반복</option><option value="analysis">분석 JSON</option></select></label><label>출력 형식<select value={String(props.options.outputFormat ?? "wav")} onChange={(event) => commit({ outputFormat: event.target.value })}><option value="wav">WAV</option><option value="mp3">MP3</option><option value="flac">FLAC</option><option value="ogg">OGG</option><option value="m4a">M4A</option></select></label><div className="two-col"><label>시작(초)<input type="number" min="0" step="0.01" value={start} onChange={(event) => commit({ start: Number(event.target.value) })} /></label><label>길이(초)<input type="number" min="0.01" step="0.01" value={duration} onChange={(event) => commit({ duration: Number(event.target.value) })} /></label></div><RangeField label="볼륨 dB" value={Number(props.options.volumeDb ?? 0)} min={-30} max={18} step={0.5} onChange={(value) => commit({ volumeDb: value, operation: "volume" })} /><div className="two-col"><label>Fade 방향<select value={String(props.options.fadeDirection ?? "in")} onChange={(event) => commit({ fadeDirection: event.target.value, operation: "fade" })}><option value="in">Fade in</option><option value="out">Fade out</option></select></label><label>Fade 초<input type="number" min="0.01" value={Number(props.options.fadeSeconds ?? 1)} onChange={(event) => commit({ fadeSeconds: Number(event.target.value), operation: "fade" })} /></label></div><div className="two-col"><label>채널<select value={String(props.options.channelMode ?? "stereo")} onChange={(event) => commit({ channelMode: event.target.value, operation: "channel" })}><option value="mono">Mono</option><option value="stereo">Stereo</option></select></label><label>Sample rate<input type="number" min="8000" value={Number(props.options.sampleRate ?? 44100)} onChange={(event) => commit({ sampleRate: Number(event.target.value) })} /></label></div><label>Bitrate kbps<input type="number" min="0" value={Number(props.options.bitrate ?? 192)} onChange={(event) => commit({ bitrate: Number(event.target.value) })} /></label><label className="checkbox-line"><input type="checkbox" checked={props.options.previewLoop === true} onChange={(event) => props.onOptions({ previewLoop: event.target.checked })} /> 선택 구간 반복</label><p className="option-note">실제 파일 변환은 Renderer가 아닌 FFmpeg Child Process에서 실행됩니다.</p></div>;
  return <FeatureLayout props={props} selectedId={selected?.handleId} onSelect={setSelected} center={center} right={right} runDisabled={ffmpeg.checked && !ffmpeg.available} runDisabledReason={ffmpeg.checked && !ffmpeg.available ? "이 배포판에는 현재 플랫폼용 FFmpeg가 포함되지 않았습니다." : undefined} />;
}
