import { useRef, useState, type PointerEvent } from "react";
import { Checkerboard, FeatureLayout, moveItem, replaceInputItems, useHistory, useMultiplePreviews, type FeatureProps } from "../shared";

type Redaction = { id: string; kind: "black" | "blur" | "pixelate" | "white"; x: number; y: number; width: number; height: number; radius?: number };

export default function ScreenshotStitchFeature(props: FeatureProps) {
  const items = props.input?.items.filter((item) => item.mimeType?.startsWith("image/") || /\.(png|jpe?g|webp)$/i.test(item.name)) ?? [];
  const previews = useMultiplePreviews(items);
  const redactions = Array.isArray(props.options.redactions) ? props.options.redactions.filter((value): value is Redaction => Boolean(value && typeof value === "object" && "id" in value)) : [];
  const [selectedId, setSelectedId] = useState<string>(); const [kind, setKind] = useState<Redaction["kind"]>("black"); const [zoom, setZoom] = useState(0.55);
  const stageRef = useRef<HTMLDivElement>(null); const drag = useRef<{ id: string; dx: number; dy: number } | undefined>(undefined);
  const history = useHistory(props.options, props.onReplaceOptions, 50);
  const commit = (patch: Record<string, unknown>) => history.commit({ ...props.options, ...patch });
  const setRedactions = (next: Redaction[]) => commit({ redactions: next });
  const updateOrder = (from: number, to: number) => props.onInput(replaceInputItems(props.input, moveItem(items, from, to)));
  const point = (event: PointerEvent<HTMLDivElement>) => { const rect = stageRef.current?.getBoundingClientRect(); return rect ? { x: Math.round((event.clientX - rect.left) / zoom), y: Math.round((event.clientY - rect.top) / zoom) } : { x: 0, y: 0 }; };
  const onDown = (event: PointerEvent<HTMLDivElement>) => { const next = point(event); const redact: Redaction = { id: crypto.randomUUID(), kind, x: next.x, y: next.y, width: 140, height: 72, radius: 12 }; setRedactions([...redactions, redact]); setSelectedId(redact.id); drag.current = { id: redact.id, dx: 0, dy: 0 }; event.currentTarget.setPointerCapture(event.pointerId); };
  const onMove = (event: PointerEvent<HTMLDivElement>) => { if (!drag.current) return; const next = point(event); props.onOptions({ redactions: redactions.map((redact) => redact.id === drag.current!.id ? { ...redact, x: Math.max(0, next.x - drag.current!.dx), y: Math.max(0, next.y - drag.current!.dy) } : redact) }); };
  const onUp = () => { if (drag.current) commit({ ...props.options }); drag.current = undefined; };
  const autoOverlap = async () => { const urls = items.map((item) => previews[item.handleId]?.url).filter((value): value is string => Boolean(value)); if (urls.length < 2) return; const estimate = await estimateOverlap(urls[0]!, urls[1]!); commit({ overlap: estimate, autoOverlap: estimate }); };
  const center = <div className="stitch-center"><div className="editor-toolbar"><button disabled={!history.canUndo} onClick={history.undo}>↶ Undo</button><button disabled={!history.canRedo} onClick={history.redo}>↷ Redo</button><button onClick={() => void autoOverlap()}>자동 겹침 탐지</button><label>Zoom<input type="range" min="0.2" max="0.8" step="0.05" value={zoom} onChange={(event) => setZoom(Number(event.target.value))} /></label></div><div className="stitch-order">{items.map((item, index) => <div className="stitch-order-item" key={item.handleId}><img src={previews[item.handleId]?.url} alt="" /><span>{index + 1}. {item.name}</span><button disabled={index === 0} onClick={() => updateOrder(index, index - 1)}>↑</button><button disabled={index === items.length - 1} onClick={() => updateOrder(index, index + 1)}>↓</button></div>)}</div><Checkerboard><div ref={stageRef} className={`stitch-stage stitch-stage--${String(props.options.direction ?? "vertical")}`} style={{ transform: `scale(${zoom})`, transformOrigin: "top left", gap: Math.max(0, Number(props.options.gap ?? 12) - Number(props.options.overlap ?? 0)) }} onPointerDown={onDown} onPointerMove={onMove} onPointerUp={onUp}>{items.map((item) => <img key={item.handleId} src={previews[item.handleId]?.url} alt={item.name} />)}{redactions.map((redact) => <button key={redact.id} className={`redaction redaction--${redact.kind}${selectedId === redact.id ? " selected" : ""}`} style={{ left: redact.x, top: redact.y, width: redact.width, height: redact.height }} onPointerDown={(event) => { event.stopPropagation(); setSelectedId(redact.id); drag.current = { id: redact.id, dx: 0, dy: 0 }; }} />)}</div></Checkerboard></div>;
  const selected = redactions.find((redact) => redact.id === selectedId);
  const right = <div><label>방향<select value={String(props.options.direction ?? "vertical")} onChange={(event) => commit({ direction: event.target.value })}><option value="vertical">세로</option><option value="horizontal">가로</option></select></label><label>크기 방식<select value={String(props.options.sizeMode ?? "first")} onChange={(event) => commit({ sizeMode: event.target.value })}><option value="first">첫 이미지 기준</option><option value="original">원본 유지</option><option value="custom">사용자 지정</option></select></label><div className="two-col"><label>간격<input type="number" min="0" value={Number(props.options.gap ?? 12)} onChange={(event) => commit({ gap: Number(event.target.value) })} /></label><label>겹침<input type="number" min="0" value={Number(props.options.overlap ?? 0)} onChange={(event) => commit({ overlap: Number(event.target.value) })} /></label></div><label>가리기 도구<select value={kind} onChange={(event) => setKind(event.target.value as Redaction["kind"])}><option value="black">검은 박스</option><option value="white">흰 박스</option><option value="blur">블러</option><option value="pixelate">픽셀화</option></select></label><label>출력 형식<select value={String(props.options.outputFormat ?? "png")} onChange={(event) => commit({ outputFormat: event.target.value })}><option value="png">PNG</option><option value="jpeg">JPEG</option><option value="webp">WebP</option></select></label>{selected && <div className="layer-properties"><h3>가리기 영역</h3><div className="two-col">{(["x", "y", "width", "height"] as const).map((key) => <label key={key}>{key}<input type="number" value={selected[key]} onChange={(event) => setRedactions(redactions.map((redact) => redact.id === selected.id ? { ...redact, [key]: Number(event.target.value) } : redact))} /></label>)}</div><button onClick={() => setRedactions(redactions.filter((redact) => redact.id !== selected.id))}>영역 삭제</button></div>}</div>;
  return <FeatureLayout props={props} center={center} right={right} />;
}

async function estimateOverlap(topUrl: string, bottomUrl: string): Promise<number> { const load = (url: string) => new Promise<HTMLImageElement>((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = reject; image.src = url; }); const [first, second] = await Promise.all([load(topUrl), load(bottomUrl)]); const width = 96; const height = 180; const canvas = document.createElement("canvas"); canvas.width = width; canvas.height = height; const context = canvas.getContext("2d"); if (!context) return 0; let best = 0; let bestScore = Number.POSITIVE_INFINITY; for (let overlap = 0; overlap <= Math.min(160, first.height, second.height); overlap += 4) { context.clearRect(0, 0, width, height); context.drawImage(first, 0, first.height - overlap, first.width, overlap, 0, 0, width, Math.max(1, overlap)); const a = context.getImageData(0, 0, width, Math.max(1, overlap)).data; context.clearRect(0, 0, width, height); context.drawImage(second, 0, 0, second.width, overlap, 0, 0, width, Math.max(1, overlap)); const b = context.getImageData(0, 0, width, Math.max(1, overlap)).data; let score = 0; for (let index = 0; index < a.length; index += 16) score += Math.abs(a[index]! - b[index]!) + Math.abs(a[index + 1]! - b[index + 1]!) + Math.abs(a[index + 2]! - b[index + 2]!); if (score < bestScore) { bestScore = score; best = overlap; } } return best; }
