import { useEffect, useMemo, useState } from "react";
import type { InputItem } from "@suwol/shared";
import { FeatureLayout, moveItem, replaceInputItems, toBlobPart, useHistory, type FeatureProps } from "../shared";

type PdfPage = { page: number; url?: string };

function usePdfPages(item?: InputItem) {
  const [pages, setPages] = useState<PdfPage[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { let active = true; const urls: string[] = []; if (!item || !window.suwol) { setPages([]); return; } setLoading(true); setError(""); void window.suwol.pdf.inspect({ handleId: item.handleId, scale: 0.18, renderThumbnails: true }).then((value) => { if (!active) return; const entries = Array.isArray(value) ? value as Array<{ page: number; data?: Uint8Array }> : []; setPages(entries.map((entry) => { const url = entry.data ? URL.createObjectURL(new Blob([toBlobPart(entry.data)], { type: "image/jpeg" })) : undefined; if (url) urls.push(url); return { page: entry.page, url }; })); }).catch((caught) => { if (active) setError(caught instanceof Error ? caught.message : "PDF 미리보기 실패"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; urls.forEach((url) => URL.revokeObjectURL(url)); }; }, [item?.handleId]);
  return { pages, error, loading };
}

export default function PdfToolsFeature(props: FeatureProps) {
  const pdfItems = props.input?.items.filter((item) => item.mimeType === "application/pdf" || item.name.toLowerCase().endsWith(".pdf")) ?? [];
  const [selectedFile, setSelectedFile] = useState<InputItem | undefined>(pdfItems[0]);
  const { pages, error, loading } = usePdfPages(selectedFile);
  const selectedPages = Array.isArray(props.options.selectedPages) ? props.options.selectedPages.filter((value): value is number => typeof value === "number") : pages.map((page) => page.page);
  const pageOrder = Array.isArray(props.options.pageOrder) ? props.options.pageOrder.filter((value): value is number => typeof value === "number") : pages.map((page) => page.page);
  const history = useHistory(props.options, props.onReplaceOptions, 50); const commit = (patch: Record<string, unknown>) => history.commit({ ...props.options, ...patch });
  const ranges = useMemo(() => selectedPages.sort((a, b) => a - b).join(","), [selectedPages]);
  const selectPage = (page: number) => { const next = selectedPages.includes(page) ? selectedPages.filter((value) => value !== page) : [...selectedPages, page]; commit({ selectedPages: next, ranges: next.sort((a, b) => a - b).join(",") }); };
  const reorderPage = (index: number, delta: number) => commit({ pageOrder: moveItem(pageOrder, index, index + delta), mode: "reorder" });
  const reorderFile = (index: number, delta: number) => props.onInput(replaceInputItems(props.input, moveItem(pdfItems, index, index + delta)));
  const center = <div className="pdf-center"><div className="editor-toolbar"><button disabled={!history.canUndo} onClick={history.undo}>↶ Undo</button><button disabled={!history.canRedo} onClick={history.redo}>↷ Redo</button><button onClick={() => commit({ mode: "merge" })}>PDF 병합</button><button onClick={() => commit({ mode: "split", ranges })}>선택 분할</button><button onClick={() => commit({ mode: "rotate", ranges, angle: 90 })}>90° 회전</button><button onClick={() => commit({ mode: "delete", ranges })}>선택 삭제</button></div>{pdfItems.length > 1 && <div className="pdf-file-order">{pdfItems.map((item, index) => <div key={item.handleId}><button onClick={() => setSelectedFile(item)}>{index + 1}. {item.name}</button><button disabled={index === 0} onClick={() => reorderFile(index, -1)}>↑</button><button disabled={index === pdfItems.length - 1} onClick={() => reorderFile(index, 1)}>↓</button></div>)}</div>}<div className="pdf-thumbnail-grid">{loading && <p>PDF.js Worker가 썸네일을 렌더링하고 있습니다…</p>}{error && <p className="error-text">{error}</p>}{pages.map((page) => <div key={page.page} className={selectedPages.includes(page.page) ? "pdf-page selected" : "pdf-page"}><button onClick={() => selectPage(page.page)}>{page.url ? <img src={page.url} alt={`Page ${page.page}`} /> : <span>{page.page}</span>}<small>페이지 {page.page}</small></button><div><button disabled={pageOrder.indexOf(page.page) <= 0} onClick={() => reorderPage(pageOrder.indexOf(page.page), -1)}>←</button><button disabled={pageOrder.indexOf(page.page) >= pageOrder.length - 1} onClick={() => reorderPage(pageOrder.indexOf(page.page), 1)}>→</button></div></div>)}</div></div>;
  const right = <div><label>작업<select value={String(props.options.mode ?? "merge")} onChange={(event) => commit({ mode: event.target.value })}><option value="merge">여러 PDF 병합</option><option value="split">선택 페이지 분할</option><option value="extract">선택 페이지 저장</option><option value="reorder">페이지 순서 적용</option><option value="rotate">페이지 회전</option><option value="delete">페이지 삭제</option><option value="pdfToImage">PDF → 이미지</option><option value="imageToPdf">이미지 → PDF</option><option value="metadata">메타데이터 확인</option><option value="metadata-edit">메타데이터 수정</option><option value="compress">압축</option><option value="watermark">텍스트 워터마크</option><option value="pageNumbers">페이지 번호</option></select></label><label>선택 페이지<input value={String(props.options.ranges ?? ranges)} onChange={(event) => commit({ ranges: event.target.value })} placeholder="1-3,5" /></label><label>회전<input type="number" step="90" value={Number(props.options.angle ?? 90)} onChange={(event) => commit({ angle: Number(event.target.value) })} /></label><label>이미지 형식<select value={String(props.options.format ?? "png")} onChange={(event) => commit({ format: event.target.value })}><option value="png">PNG</option><option value="jpeg">JPEG</option></select></label><label>페이지 크기<select value={String(props.options.pageSize ?? "image-fit")} onChange={(event) => commit({ pageSize: event.target.value })}><option value="image-fit">이미지 맞춤</option><option value="original">원본</option><option value="a4">A4</option><option value="letter">Letter</option></select></label><label>제목<input value={String(props.options.title ?? "")} onChange={(event) => commit({ title: event.target.value })} /></label><label>작성자<input value={String(props.options.author ?? "")} onChange={(event) => commit({ author: event.target.value })} /></label><label>워터마크<input value={String(props.options.text ?? "")} onChange={(event) => commit({ text: event.target.value })} /></label><p className="option-note">암호화 PDF 생성은 현재 cross-platform adapter에서 지원하지 않습니다. 해당 옵션은 노출하지 않습니다.</p></div>;
  return <FeatureLayout props={props} selectedId={selectedFile?.handleId} onSelect={setSelectedFile} center={center} right={right} />;
}
