import { useMemo, useRef, useState } from "react";
import type { InputItem } from "@suwol/shared";
import { FeatureLayout, RangeField, useFfmpegAvailability, useHandlePreview, useHistory, type FeatureProps } from "../shared";

export default function VideoToGifWebpFeature(props: FeatureProps) {
  const videos = props.input?.items.filter((item) => item.mimeType?.startsWith("video/") || /\.(mp4|webm|mov|mkv)$/i.test(item.name)) ?? [];
  const [selected, setSelected] = useState<InputItem | undefined>(videos[0]); const preview = useHandlePreview(selected, 32 * 1024 * 1024); const [sourceDuration, setSourceDuration] = useState(0); const video = useRef<HTMLVideoElement>(null);
  const ffmpeg = useFfmpegAvailability();
  const history = useHistory(props.options, props.onReplaceOptions, 50); const commit = (patch: Record<string, unknown>) => history.commit({ ...props.options, ...patch });
  const start = Number(props.options.start ?? 0); const duration = Number(props.options.duration ?? Math.min(10, sourceDuration || 10)); const width = Number(props.options.width ?? 640); const height = Number(props.options.height ?? 0); const fps = Number(props.options.fps ?? 12); const quality = Number(props.options.quality ?? 80);
  const estimate = useMemo(() => { if (!selected || !sourceDuration) return undefined; const temporal = Math.min(1, duration / sourceDuration); const dimensions = Math.max(0.15, (width * (height || width * 9 / 16)) / (1280 * 720)); const format = props.options.outputFormat === "webp" ? 0.65 : 1; return Math.max(8 * 1024, Math.round((selected.size ?? 0) * temporal * dimensions * (quality / 100) * format)); }, [selected, sourceDuration, duration, width, height, quality, props.options.outputFormat]);
  const center = <div className="video-center"><div className="editor-toolbar"><button disabled={!history.canUndo} onClick={history.undo}>↶ Undo</button><button disabled={!history.canRedo} onClick={history.redo}>↷ Redo</button><button onClick={() => { if (video.current) { video.current.currentTime = start; void video.current.play(); } }}>선택 구간 미리보기</button></div>{preview.url ? <video ref={video} controls src={preview.url} onLoadedMetadata={(event) => { setSourceDuration(event.currentTarget.duration); if (!props.options.duration) props.onOptions({ duration: Math.min(10, event.currentTarget.duration) }); }} onTimeUpdate={(event) => { if (event.currentTarget.currentTime > start + duration) event.currentTarget.pause(); }} /> : <p>{preview.loading ? "영상 미리보기 로드 중…" : preview.error ?? "영상을 선택하세요."}</p>}<div className="timeline-selection"><label>시작 {start.toFixed(1)}s<input type="range" min="0" max={Math.max(0, sourceDuration - 0.1)} step="0.1" value={start} onChange={(event) => commit({ start: Number(event.target.value) })} /></label><label>길이 {duration.toFixed(1)}s<input type="range" min="0.1" max={Math.min(30, Math.max(0.1, sourceDuration - start || 30))} step="0.1" value={duration} onChange={(event) => commit({ duration: Number(event.target.value) })} /></label></div><p className="option-note">예상 결과 크기: {estimate ? `약 ${(estimate / 1024 / 1024).toFixed(1)} MB (추정값)` : "영상 메타데이터를 읽은 뒤 표시"}</p></div>;
  const crop = props.options.crop && typeof props.options.crop === "object" ? props.options.crop as Record<string, unknown> : {};
  const right = <div><label>출력<select value={String(props.options.outputFormat ?? "gif")} onChange={(event) => commit({ outputFormat: event.target.value })}><option value="gif">GIF</option><option value="webp">Animated WebP</option></select></label><div className="two-col"><label>시작(초)<input type="number" min="0" step="0.1" value={start} onChange={(event) => commit({ start: Number(event.target.value) })} /></label><label>길이(초)<input type="number" min="0.1" max="30" step="0.1" value={duration} onChange={(event) => commit({ duration: Number(event.target.value) })} /></label></div><RangeField label="FPS" value={fps} min={1} max={24} onChange={(value) => commit({ fps: value })} /><div className="two-col"><label>너비<input type="number" min="2" value={width} onChange={(event) => commit({ width: Number(event.target.value) })} /></label><label>높이<input type="number" min="0" value={height} onChange={(event) => commit({ height: Number(event.target.value) })} /></label></div><label className="checkbox-line"><input type="checkbox" checked={props.options.keepAspectRatio !== false} onChange={(event) => commit({ keepAspectRatio: event.target.checked })} /> 비율 유지</label><div className="two-col"><label>Crop X<input type="number" min="0" value={Number(crop.x ?? 0)} onChange={(event) => commit({ crop: { ...crop, x: Number(event.target.value) } })} /></label><label>Crop Y<input type="number" min="0" value={Number(crop.y ?? 0)} onChange={(event) => commit({ crop: { ...crop, y: Number(event.target.value) } })} /></label><label>Crop W<input type="number" min="0" value={Number(crop.width ?? 0)} onChange={(event) => commit({ crop: { ...crop, width: Number(event.target.value) } })} /></label><label>Crop H<input type="number" min="0" value={Number(crop.height ?? 0)} onChange={(event) => commit({ crop: { ...crop, height: Number(event.target.value) } })} /></label></div><label>회전<select value={String(props.options.rotate ?? 0)} onChange={(event) => commit({ rotate: Number(event.target.value) })}><option value="0">없음</option><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></label><RangeField label="품질" value={quality} min={1} max={100} onChange={(value) => commit({ quality: value })} /><label>반복<select value={String(props.options.loop ?? true)} onChange={(event) => commit({ loop: event.target.value === "true" })}><option value="true">반복</option><option value="false">1회</option></select></label><p className="option-note">진행률, 취소, 임시 파일 정리는 공통 JobQueue와 FFmpeg Worker가 처리합니다.</p></div>;
  return <FeatureLayout props={props} selectedId={selected?.handleId} onSelect={setSelected} center={center} right={right} runDisabled={ffmpeg.checked && !ffmpeg.available} runDisabledReason={ffmpeg.checked && !ffmpeg.available ? "이 배포판에는 현재 플랫폼용 FFmpeg가 포함되지 않았습니다." : undefined} />;
}
