import { useEffect, useMemo, useState } from "react";
import type { InputItem } from "@suwol/shared";
import { FeatureLayout, moveItem, toBlobPart, useFfmpegAvailability, useHistory, type FeatureProps } from "../shared";

type Frame = { index: number; delayMs: number; url?: string };

function useGifFrames(item?: InputItem) {
  const [frames, setFrames] = useState<Frame[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { let active = true; const urls: string[] = []; if (!item || !window.suwol) { setFrames([]); return; } setLoading(true); setError(""); void window.suwol.media.inspectGif({ handleId: item.handleId }).then((value) => { if (!active) return; const raw = value as { frames?: Array<{ index: number; delayMs: number; data?: Uint8Array }> }; setFrames((raw.frames ?? []).map((frame) => { const url = frame.data ? URL.createObjectURL(new Blob([toBlobPart(frame.data)], { type: "image/png" })) : undefined; if (url) urls.push(url); return { index: frame.index, delayMs: frame.delayMs, url }; })); }).catch((caught) => { if (active) setError(caught instanceof Error ? caught.message : "GIF 프레임을 읽지 못했습니다."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; urls.forEach((url) => URL.revokeObjectURL(url)); }; }, [item?.handleId]);
  return { frames, error, loading };
}

export default function GifFrameEditorFeature(props: FeatureProps) {
  const source = props.input?.items.find((item) => item.mimeType === "image/gif" || /\.gif$/i.test(item.name)); const { frames, error, loading } = useGifFrames(source);
  const ffmpeg = useFfmpegAvailability();
  const order = Array.isArray(props.options.frameOrder) ? props.options.frameOrder.filter((value): value is number => typeof value === "number") : frames.map((frame) => frame.index);
  const delays = props.options.frameDelays && typeof props.options.frameDelays === "object" ? props.options.frameDelays as Record<string, number> : {};
  const [current, setCurrent] = useState(0); const [playing, setPlaying] = useState(false); const [windowStart, setWindowStart] = useState(0);
  const history = useHistory(props.options, props.onReplaceOptions, 50); const commit = (patch: Record<string, unknown>) => history.commit({ ...props.options, ...patch });
  const ordered = useMemo(() => order.map((index) => frames.find((frame) => frame.index === index)).filter((value): value is Frame => Boolean(value)), [order, frames]);
  useEffect(() => { if (!playing || ordered.length === 0) return; const frame = ordered[current % ordered.length]!; const timer = setTimeout(() => setCurrent((value) => (value + 1) % ordered.length), Math.max(20, delays[String(frame.index)] ?? frame.delayMs)); return () => clearTimeout(timer); }, [playing, current, ordered, delays]);
  const setOrder = (next: number[]) => commit({ frameOrder: next, frameRange: next.map((value) => value + 1).join(",") });
  const active = ordered[current % Math.max(1, ordered.length)]; const visible = ordered.slice(windowStart, windowStart + 60);
  const center = <div className="gif-center"><div className="editor-toolbar"><button disabled={!history.canUndo} onClick={history.undo}>↶ Undo</button><button disabled={!history.canRedo} onClick={history.redo}>↷ Redo</button><button onClick={() => setPlaying((value) => !value)}>{playing ? "일시정지" : "재생"}</button><button disabled={current <= 0} onClick={() => setCurrent((value) => Math.max(0, value - 1))}>이전</button><button disabled={current >= ordered.length - 1} onClick={() => setCurrent((value) => Math.min(ordered.length - 1, value + 1))}>다음</button></div><div className="gif-player">{active?.url ? <img src={active.url} alt={`Frame ${active.index + 1}`} /> : <p>{loading ? "프레임을 Worker에서 읽는 중…" : error || "GIF를 선택하세요."}</p>}<small>{active ? `${current + 1} / ${ordered.length} · ${delays[String(active.index)] ?? active.delayMs}ms` : ""}</small></div><div className="gif-window-controls"><button disabled={windowStart === 0} onClick={() => setWindowStart((value) => Math.max(0, value - 60))}>이전 60</button><span>{windowStart + 1}–{Math.min(ordered.length, windowStart + 60)} / {ordered.length}</span><button disabled={windowStart + 60 >= ordered.length} onClick={() => setWindowStart((value) => value + 60)}>다음 60</button></div><div className="gif-frame-grid">{visible.map((frame, localIndex) => { const index = windowStart + localIndex; return <div className={index === current ? "gif-frame selected" : "gif-frame"} key={`${frame.index}-${index}`}><button onClick={() => setCurrent(index)}><img src={frame.url} alt={`Frame ${index + 1}`} /><small>{index + 1}</small></button><input type="number" min="20" value={delays[String(frame.index)] ?? frame.delayMs} onChange={(event) => commit({ frameDelays: { ...delays, [String(frame.index)]: Number(event.target.value) } })} /><div><button disabled={index === 0} onClick={() => setOrder(moveItem(order, index, index - 1))}>←</button><button disabled={index === order.length - 1} onClick={() => setOrder(moveItem(order, index, index + 1))}>→</button><button onClick={() => setOrder(order.filter((_, orderIndex) => orderIndex !== index))}>×</button><button onClick={() => setOrder([...order.slice(0, index + 1), frame.index, ...order.slice(index + 1)])}>복제</button></div></div>; })}</div></div>;
  const right = <div><label>저장 방식<select value={String(props.options.mode ?? "gif")} onChange={(event) => commit({ mode: event.target.value })}><option value="gif">편집 GIF</option><option value="zip">PNG 프레임 ZIP</option></select></label><label>전체 지연 시간(ms)<input type="number" min="20" value={Number(props.options.delayMs ?? 83)} onChange={(event) => commit({ delayMs: Number(event.target.value), frameDelays: Object.fromEntries(ordered.map((frame) => [String(frame.index), Number(event.target.value)])) })} /></label><label>반복<select value={String(props.options.loopCount ?? (props.options.loop === false ? 1 : 0))} onChange={(event) => commit({ loopCount: Number(event.target.value), loop: Number(event.target.value) !== 1 })}><option value="0">무한</option><option value="1">한 번</option><option value="2">2회</option><option value="3">3회</option></select></label><div className="two-col"><label>너비<input type="number" min="0" value={Number(props.options.width ?? 0)} onChange={(event) => commit({ width: Number(event.target.value) })} /></label><label>높이<input type="number" min="0" value={Number(props.options.height ?? 0)} onChange={(event) => commit({ height: Number(event.target.value) })} /></label></div><label>출력 프레임 형식<select value={String(props.options.outputFormat ?? "png")} onChange={(event) => commit({ outputFormat: event.target.value })}><option value="png">PNG</option><option value="jpeg">JPEG</option><option value="webp">WebP</option></select></label></div>;
  const needsFfmpeg = String(props.options.mode ?? "gif") === "gif";
  return <FeatureLayout props={props} selectedId={source?.handleId} center={center} right={right} runDisabled={needsFfmpeg && ffmpeg.checked && !ffmpeg.available} runDisabledReason={needsFfmpeg && ffmpeg.checked && !ffmpeg.available ? "GIF 재인코딩에는 포함된 FFmpeg가 필요합니다. PNG ZIP은 FFmpeg 없이 저장할 수 있습니다." : undefined} />;
}
