import { useState } from "react";
import { FeatureLayout, type FeatureProps } from "../shared";

type RemoteMode = "headers" | "redirect" | "open-graph" | "dns" | "tls" | "port" | "url-parse";
type LocalMode = "ip" | "ports" | "trace" | "certificate";
type Mode = RemoteMode | LocalMode;

export default function NetworkToolsFeature(props: FeatureProps) {
  const [mode, setMode] = useState<Mode>("headers"); const [value, setValue] = useState("https://example.com"); const [recordType, setRecordType] = useState("A"); const [port, setPort] = useState(443); const [prefix, setPrefix] = useState("24"); const [protocol, setProtocol] = useState<"all" | "TCP" | "UDP">("all"); const [requestId, setRequestId] = useState(""); const [result, setResult] = useState<unknown>(); const [error, setError] = useState(""); const [elapsed, setElapsed] = useState<number>(); const [working, setWorking] = useState(false);
  const local = (candidate: Mode): candidate is LocalMode => ["ip", "ports", "trace", "certificate"].includes(candidate);
  const run = async () => { if (!window.suwol) return; const id = `network-${Date.now()}`; setRequestId(id); setWorking(true); setError(""); setResult(undefined); const started = performance.now(); try { const next = local(mode) ? await window.suwol.network.local({ mode, value, prefix, protocol }) : await window.suwol.network.request({ url: value.trim(), mode, requestId: id, recordType, port }); setElapsed(Math.round(performance.now() - started)); setResult(next); } catch (caught) { setError(caught instanceof Error ? caught.message : "네트워크 검사에 실패했습니다."); } finally { setWorking(false); } };
  const serialized = result === undefined ? "" : JSON.stringify(result, null, 2);
  const center = <div className="network-center"><div className="network-policy"><strong>안전한 Main Process 요청</strong><span>Renderer fetch를 사용하지 않습니다. http/https, 공개 IP, redirect 목적지, DNS rebinding, timeout, 응답 크기를 모두 Main에서 검증합니다.</span></div><textarea className="network-input" value={value} onChange={(event) => setValue(event.target.value)} placeholder={mode === "certificate" ? "-----BEGIN CERTIFICATE-----" : mode === "trace" ? "ping / traceroute 결과" : mode === "ip" ? "192.168.0.10/24" : "https://example.com"} /><div className="button-row"><button className="run-button" disabled={working} onClick={() => void run()}>{working ? "검사 중…" : "검사 실행"}</button>{working && <button className="secondary-button" onClick={() => void window.suwol?.network.cancel(requestId)}>취소</button>}{serialized && <><button className="secondary-button" onClick={() => void window.suwol?.clipboard.writeText(serialized)}>클립보드 복사</button><button className="secondary-button" onClick={() => void window.suwol?.files.saveText({ value: serialized, defaultName: `network-${mode}.json` })}>JSON 저장</button></>}</div>{elapsed !== undefined && <p className="option-note">응답 시간: {elapsed}ms</p>}{error && <p className="error-text">{error}</p>}{serialized && <pre className="code-result">{serialized}</pre>}</div>;
  const right = <div><label>검사<select value={mode} onChange={(event) => setMode(event.target.value as Mode)}><optgroup label="로컬 분석"><option value="ip">IPv4 subnet</option><option value="ports">일반 포트 검색</option><option value="trace">Ping / Trace 텍스트</option><option value="certificate">PEM 인증서</option></optgroup><optgroup label="제한된 공개 네트워크"><option value="url-parse">URL 파싱</option><option value="dns">DNS 조회</option><option value="headers">HTTP 헤더</option><option value="redirect">Redirect 경로</option><option value="open-graph">Open Graph</option><option value="tls">TLS 인증서</option><option value="port">허용 포트 연결</option></optgroup></select></label>{mode === "dns" && <label>레코드<select value={recordType} onChange={(event) => setRecordType(event.target.value)}>{["A", "AAAA", "CNAME", "MX", "TXT", "NS", "SOA", "CAA"].map((value) => <option key={value}>{value}</option>)}</select></label>}{mode === "port" && <label>포트<input type="number" min="1" max="65535" value={port} onChange={(event) => setPort(Number(event.target.value))} /></label>}{mode === "ip" && <label>Prefix<input value={prefix} onChange={(event) => setPrefix(event.target.value)} /></label>}{mode === "ports" && <label>프로토콜<select value={protocol} onChange={(event) => setProtocol(event.target.value as typeof protocol)}><option value="all">TCP + UDP</option><option value="TCP">TCP</option><option value="UDP">UDP</option></select></label>}<p className="option-note">localhost, 사설망, link-local, metadata IP와 허용되지 않은 포트는 차단됩니다.</p></div>;
  return <FeatureLayout props={props} center={center} right={right} showOutput={false} />;
}
